### ISSUE TITLE
Wizard Spell Master: Arcane Depth doesn't work if you spend Arcane Recovery

### ISSUE THREAD

**Issue by EnderWiggin** [SolastaMods/SolastaCommunityExpansion#1122]
Unlimited Arcane Depth turned on, Arcane Depth shows that it has uses and there's option to use it when doing short rest, but it does nothing. If Arcane Recovery isn't spent then Arcane Depth works as advertised.

**Comment by ThyWoof** [comment]
Curious if MC is installed as it also touches slots recovery on short rest.

**Comment by EnderWiggin** [comment]
Yes, enabled.

**Comment by EnderWiggin** [comment]
Did quick test - Arcane Recovery does not affect Arcane Depth. Arcane Depth does not work if MC is turned on and works fine if it is turned off, regardless of whether Arcane Recovery was used.
