### ISSUE TITLE
ISSUE: After mod update, saves from previous version doesn't load and are deleted.

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1151]
Hi,

I've looked at changelog, and I might find issue with your decision to temporarily remove Ancient Pact from Warlock list - at least I discovered this, since it was introduced at version 1.3.44.6 and I used that subclass, (good I'm doing backups, before updating, but many people could suffer) my saves were deleted and not loading any more. I believe it should be somehow still present and available if picked before, but not possible to pick for next characters till fixes comes, that way you won't break people saves :)

I hope it somehow helps your project, you're doing wonderful job!

**Comment by ThyWoof** [comment]
Fixed on 1.3.44.8
