### ISSUE TITLE
Invalid fix of Wise Defense

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1177]
Hi, again great job people! 👍 

However, I think someone did some mistake at last update.

I'm talking about:
`Fix Wise Defense adding charisma instead of wisdom`
There is another feat called: 'Charismatic Defense' which basically now do the same. I believe Wise Defense should stay as it was, but maybe I am mistaken about that one.

Have a great day! 👍  😄

**Comment by ThyWoof** [comment]
Charismatic Defense adds Charisma +1 and defense based on CHA;
Wise Defense adds Wisdom +1 and defense based on WIS;

**Comment by GuazP** [comment]
I see, I understood it wrongly then, like there was fix changing Wise Defense as defense based on WIS. Thank you for clarification.
