### ISSUE TITLE
Monsters are broken : Monsters not present in 1.3.44.10, 1.3.44.11, 1.3.46.0

### ISSUE THREAD

**Issue by DubhHerder** [SolastaMods/SolastaCommunityExpansion#1185]
no monsters and no monster dll sidercar in release. This would ruin any dungeon that used them. The sidecar idea is obviously unreliable and should be abandoned because of this major flaw 

This is obviously a bug rather than deliberate decision as removing content unilaterally and without notification (or update in changelog) because of bug reports would go against the philosophy of the mod as a "community effort where everything is optional".

The files in the side car do not match the files from PR #947 and the sidecar in general should be removed. Instead PR#947 should be reinstated

**Comment by ThyWoof** [comment]
fixed on https://github.com/SolastaMods/SolastaCommunityExpansion/pull/1195
