### ISSUE TITLE
Level Down: Sorcerer metamagic isn't taken from character

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1193]
When using multiple level down, you can select other metamagic from sorcerer class, old ones are still in place.
(Tested on version: 1.3.46.0)

**Comment by ThyWoof** [comment]
Cannot Reproduce...
![image](https://user-images.githubusercontent.com/13087646/164872927-18a91ac1-f6b9-4511-9442-421d7821f4ae.png)


![image](https://user-images.githubusercontent.com/13087646/164872933-95ac22cc-98ae-4d9a-acd6-54144576fc1b.png)

After Level Down from 3 to 2 and Level Up again.
![image](https://user-images.githubusercontent.com/13087646/164872948-24a257c1-4b68-4250-be27-25262049f712.png)

**Comment by GuazP** [comment]
I'll try again, if I will be able to reproduce, I'll attach steps there, maybe I did something between what caused this 🤔
