### ISSUE TITLE
Warlock level up: Duplicates and multiple additional eldritch invocations

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1194]
When leveling Warlock, after 2nd level, every next level you can choose new invocation from class selection screen (just open again dropdown menu at right side where class details are), old one wasn't removed, however, changing these is nice thing as some optional rules allow to retrain such things.

This works for Warlock after 3rd level with Pact Boon. 

(Tested on version 1.3.46.0)

**Comment by ThyWoof** [comment]
Fixed on 1.3.46.2
