### ISSUE TITLE
'Moving' Eldritch Blast: Flying oponent pushed by repelling blast doesn't fall when it looses concentration.

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1200]
![image](https://user-images.githubusercontent.com/33330881/164801142-4f9ba8d7-86d3-43fb-892c-6f32790c817b.png)
As shown at screenshot, flying oponent landed on elevation, when repelling blast pushed him of the edge, then he loosed concentration after that, he ends up stuck in the air with falling animation.

During 'infinite falling', enemy is unable to do anything or act at any way, he just ends his turn.

(Version 1.3.46.1)

**Comment by ThyWoof** [comment]
It sounds like a very collateral case. A save would help.

**Comment by GuazP** [comment]
I'll check if I still have autosave from just before this fight. If I do, I'll attach steps to reproduce as well. (But currently I'm not on PC with steam, please hold ticket open for tomorrow evening - Europe time)

**Comment by GuazP** [comment]
Unfortunately, I don't have this save, and it's hard to recreate because AI have to take specific action. However, I'll try to record issue with 30 second back clip and catch autosave whenever it occurs again.
