### ISSUE TITLE
Level Down: When level down is used and decrease character to 'level 0',

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1201]
![image](https://user-images.githubusercontent.com/33330881/164814986-df10c030-9e91-43b5-9a0a-663c8a580ac7.png)
From this point, after accepting mod warning, further play, exit from this screen or literally do anything beside Alt+F4 isn't possible. I believe level down should be disabled for removing last level or if there is any other way to just rebase classes, without changing background, apperance, backstory etc. this would be awesome.

**Comment by ThyWoof** [comment]
It will RESPEC now if level 1.
