### ISSUE TITLE
Level Down: Dices used by characters doesn't vanish according to actual level.

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1202]
Hi,
I believe that's new issue as this I recall working at version 1.3.44.5 (but my memory could be faulty about that).

![image](https://user-images.githubusercontent.com/33330881/164815380-f99dfaa6-3299-4008-8a0c-990e79371de6.png)

Dices attached to screenshot, doesn't vanish when level down is clicked.

**Comment by ThyWoof** [comment]
Level down was on short rest before reason why. Won't fix this as too much trouble for such a small visual glitch. It isn't like people are leveling down on every rest.
