### ISSUE TITLE
"auto pause after combat" option can hang the game if a cut scene would auto play.

### ISSUE THREAD

**Issue by WolffHobbitStomper** [SolastaMods/SolastaCommunityExpansion#1215]
The "auto pause after combat" option can hang the game if a cut scene would auto play.
Attached is a save from the end of the CoTM campaign, just before this happens.

NB. This save was from 1.3.46.2 dev branch with some local changes (extra crafting recpies for rapiers). 
I get a mod stability warning when loading the save using 1.3.47.0 and a game hangs. 
I've included my local changes in the zip from today's dev so you can make a build that will load the save (still get the stability warning, but save loads OK).
Feel free to merge the extra rapier recipes into the CE if you want
[Files.zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/8597865/Files.zip)
.

**Comment by ThyWoof** [comment]
Rapier recipes added. Thanks

**Comment by ThyWoof** [comment]
Still researching how to fix the auto pause.

**Comment by ThyWoof** [comment]
This is a hard one to fix so will add a disclaimer on mod UI
