### ISSUE TITLE
Issue - Bolgrif race can't choose druidic cantrip

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1238]
![image](https://user-images.githubusercontent.com/33330881/167314147-6c123f88-e45e-4640-a2e4-50fb4e0e7f64.png)

CE Version: BETA for 1.3.47-207-1-3-50-3

Hi, as at the attached screenshot, during character respec, when I choose Bolgrif race I can't pick any of druidic cantrip. Idk if that's the case, I have choosed Ranger class.

**Comment by ThyWoof** [comment]
Fixed on 1.3.50.11
