### ISSUE TITLE
Issue - Warlock Ancient Forest Pact can double-pick spells

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1239]
![image](https://user-images.githubusercontent.com/33330881/167315247-042d79cf-c4b3-459c-9f12-5099d7328600.png)

Hi,

As seen at screenshot, during respec, Warlock from Ancient Forest Pact can pick spells which should be given as granted from chosen subclass. In that case, these are 'Entangle' and 'Goodberry'.

**Comment by ThyWoof** [comment]
fixed on latest.
