### ISSUE TITLE
Issue - Vanishing items when respec

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1240]
Hi,

If chracter have some kind of better carrying capacity item (like Handy Haversack) and character goes to respec with heavy load, then some items which going to be de-equiped are lost. In that example there were boots which mitigate heavy load + Dwarven Plate (pretty painful, but happens). 
I believe it's kind of rare event when someone have these boots equiped, are heavy loaded and do respec, but it could happen, so I report that :)

**Comment by ThyWoof** [comment]
Please get latest shared build from our discord channel and test again.

**Comment by ThyWoof** [comment]
fixed on 1.3.50.12
