### ISSUE TITLE
High Elf - Warlock is stuck and can't go to picking spells, buttons become inactive.

### ISSUE THREAD

**Issue by GuazP** [SolastaMods/SolastaCommunityExpansion#1246]
![image](https://user-images.githubusercontent.com/33330881/167508249-012f0da3-d0f9-4014-85f0-65989f6aea13.png)
![image](https://user-images.githubusercontent.com/33330881/167508266-14b64e34-928b-46ae-ac93-7ac38b067c05.png)
![image](https://user-images.githubusercontent.com/33330881/167508288-7a6c1515-e898-42fa-b730-e2fabfcbca84.png)
![image](https://user-images.githubusercontent.com/33330881/167508305-6e576256-2801-459a-b396-83f5b927aa2f.png)
![image](https://user-images.githubusercontent.com/33330881/167508311-5d9e4539-db02-43bc-ac00-59c229eefb1e.png)

Noted on version .14 shared on QA (idk why, but discord shows these screenshots as inappropriate)

Steps to reproduce in screenshots. Generally after that only one option is to cancel whole process, go previous or change something doesn't work at all. If cancel would not work either, only restart could bring game up :)

**Comment by ThyWoof** [comment]
fixed on 15.
