### ISSUE TITLE
Combat stops when Brood of Blood is about to attack in Aksha fight with CE installed

### ISSUE THREAD

**Issue by adowdy** [SolastaMods/SolastaCommunityExpansion#1277]
Hey guys, enjoying the game and wanted to play with the incredibly expansive Community Expansion mod. Great work making some cool things that add to the experience!

I got about 20 hours in with very minimal issues while toggling on most but not all of the CE content in the mod configuration window -- but I'm now stuck when trying to complete the Aksha fight. Whenever her minions ("Brood of Blood/Dread") are about to take their turn in the carousel, I get the dreaded "error occured in a mod" instability warning. The game does not crash, but combat just stops, and I can't continue to take turns (indefinite 'halted' combat, but game is not paused.).

I reinitiated the fight a few times and got different initiative orderings, but the same result happens whenever I finish one of my party turns (and the next actor in the turn order is a Brood enemy)

I think the option of 'turning off all mods' doesn't work as yet for me because my characters are using some mod features. Turning it off prevents me from loading my save, which I honestly expected.

Let me try to provide the files + info you guys ask for here:

Mod Manager version 0.24.2.0
Game version is the latest on Steam right now  1.3.53 public
Community Expansion 2 version used is 1.3.53.1

i tried to filter down to 2 recent saves - one is the autosave when the fight started, one is after i convinced akasha to let me seek an audience and pass by her - from which if you 'loot' her chest she attacks, then the bug can be reproduced.

Also a few screenshots of what it looks like when i finish a turn and the Brood enemies are about to go are in the zip

[solasta-aksha-error.zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/8694702/solasta-aksha-error.zip)

I don't know how realistic it is that this gets fixed (this log doesn't look like a smoking gun to me), but even so - thanks for looking at my post!

For now I will skip trying to fight this boss and continue (since there was the option for 'diplomacy' here). I'll see if I hit similar snags elsewhere

**Comment by ThyWoof** [comment]
Fixed.

**Comment by adowdy** [comment]
Thanks @ThyWoof  you are a wizard
