### ISSUE TITLE
Feaature request: increase thrown weapons range

### ISSUE THREAD

**Issue by iccicci** [SolastaMods/SolastaCommunityExpansion#1299]
First of all: great mod! Thank you!
Second point: awesome mod! Good job!

Once said that: thrown weapons have a so short rage which makes them almost useless. Is it possible to add an option to increase their range?
Or if that option is already there, could you please point me where it is? I nvaigated all the tabs but I wasn't able to find anything related.

Thank you in advance.

P.S.
Sorry, I forgot to say how much great this mod is, it makes Solasta as it would have been!

**Comment by ThyWoof** [comment]
@EnderWiggin , as you are working on custom items do you believe this is easy to implement?
