### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by FungJiHsu** [SolastaMods/SolastaCommunityExpansion#1319]
The ablities of [Monk - Way of the Distant Hand] dont apply to Enchanted_Longbow/Enchanted_Shortbow, only original version can work
[TEST.zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/8798257/TEST.zip)
.
May be annoying.
Previous request:
Is there anyway to make stacksize bigger (99 or 999)?
Would it be possible to make classes [LEARN ONE spell] instead of [UNLEARN ONE spell then LEARN TWO spells] when levelup?

**Comment by ThyWoof** [comment]
We cannot reproduce on latest QA release. No plans to change stack size of change how spells are learned .
