### ISSUE TITLE
New Deadeye feat is causing multiplayer desyncs & disabling advantage

### ISSUE THREAD

**Issue by Lesamuen** [SolastaMods/SolastaCommunityExpansion#1340]
First issue: when deadeye is disabled on the client's side and the condition ends, all other clients seem to see the condition not end. This causes a situation where the client misses due to the -5 and everyone else sees a hit, which kills the enemy for everyone else but not for the client, causing a severe desync. (Everyone went to sleep after that so I am unable to test how to reproduce it at the moment)

Second issue: when the deadeye feat is taken, whether the condition is enabled or not, _all_ sources of advantage and disadvantage are disabled. This includes attacking from stealth (I took the feat on a rogue), prone, and paralyzation (I put an enemy to sleep with the party wizard). I suspect this is due to the implementation of the "long range no longer confers disadvantage" part. This issue is present in both multiplayer and singleplayer.

Version is 1.3.57.0C, on Solasta 1.3.57

**Comment by Lesamuen** [comment]
Version is 1.3.57.0C

**Comment by Lesamuen** [comment]
Nothing is showing up in the logs as well (for the second issue; couldn't get the logs for the first issue the first time around). "AttackMain", "HandleCharacterAttack", and "HandleCharacterAttackDamage" are going off fine with no error messages whatsoever.

**Comment by EnderWiggin** [comment]
Second issue is indeed wrong implementation - instead of removing long range disadvantage it removes all advantage and disadvantage on ranged attacks, like Take Aim does.
