### ISSUE TITLE
Sorcerer + warlock multiclass question (bug)?

### ISSUE THREAD

**Issue by adowdy** [SolastaMods/SolastaCommunityExpansion#1351]
Hello! I'm using the Community mod warlock class, multiclassed with my sorcerer (lock 2 + sorc 3, total level =5 ). RAW for sorlocks in 5e, I thought taking the 3rd level in sorcerer should give me 'normal' sorcerer spell progression (2 second level spell slots and can learn sorc spells from 2nd level set.

I have the 2 second level spell slots, but i couldn't learn any 2nd level spells known when i took the 3rd level in sorcerer. Is this intended or a bug?

Can attach extra info if this is considered an issue to look into. Thanks, cheers!

**Comment by ThyWoof** [comment]
We cannot reproduce so a save always help

**Comment by adowdy** [comment]
Hmm, I reloaded my save before the levelup and now I do see the 2nd level spell selections - having trouble reproducing myself.

I'll throw the saves here, but at least it looks like I'm not stuck on my character build since I can redo the levelup sequence

[AutoSave_3.zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/8838574/AutoSave_3.zip)

If this isn't enough to go on, feel free to close this out for now

**Comment by adowdy** [comment]
I did reproduce again: when i levelled up to lv 6, my sor/lock cannot select to learn a new level 2 spell (spells known).

And curiously, when I opted not to complete the level, and instead saved my game - then closed the game client completely and reopened my save, then re-initiated the levelup -- only then can i select new level 2 spells to learn.
