### ISSUE TITLE
Updating to 1G from 1F completely reset my settings file

### ISSUE THREAD

**Issue by Lesamuen** [SolastaMods/SolastaCommunityExpansion#1372]
I downloaded it manually and put it into UMM instead of using the new in-mod autoupdater, so that might be why.
Every single option got unticked, including all races, subclasses, spells, and feats.

I happened to have a backup, so I restored it and downgraded back to 1F.

**Comment by ThyWoof** [comment]
Auto update doesn’t touch settings at all.
