### ISSUE TITLE
Dark-Elf displaying twice on Character Creation menu

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaCommunityExpansion#1428]
Half-Elf also oddly showing up now as an optional race.  This used to say "Dark Elf" I think.

Running latest update.  1.3.57.3G.

**Comment by ThyWoof** [comment]
Not a bug. We cannot afford adding Half Elf variants to official Half Elf. Dark Elf still under Elf (unfortunately this one cannot be enable / disable on mod UI settings)

**Comment by Mamotromico** [comment]
Hey @ThyWoof, sorry to necro this but it seems better than to open a new issue to ask. Is this a technical limitation? Or is it more on the realm of "Took much work for too little gain"?

**Comment by ThyWoof** [comment]
Not dark elf. It’s expected to have 2 half elf as I don’t wanna mess with vanilla one

**Comment by Mamotromico** [comment]
Sorry, I realize I wasn't clear. I was asking about merging the new variants with the official races (so half-elf / tieflings), if that's more of a technical limitation or just something too prone to break that it's not worth it.

**Comment by ThyWoof** [comment]
If I do so I’ll break vanilla heroes.

**Comment by Mamotromico** [comment]
Got it! Thanks for the explanation.
