### ISSUE TITLE
Monk AC seems broken

### ISSUE THREAD

**Issue by CSal90066** [SolastaMods/SolastaCommunityExpansion#1440]
It appears I am not getting all of my AC stacks from feats, etc.  I've leveled up in-between grabs, but you'll get the picture (pun).
Thanks,
-CSal
![Error-Monk1](https://user-images.githubusercontent.com/107894791/174688946-f42f1ed8-076e-4f23-ad44-d3695cbc3f43.png)
![Error-Monk2](https://user-images.githubusercontent.com/107894791/174688957-19809fbd-1867-48dc-a451-212eb47cf99d.png)
![Error-Monk3](https://user-images.githubusercontent.com/107894791/174688964-d755ba89-9b6d-4556-8c72-fc9209cb83fa.png)

**Comment by CSal90066** [comment]
BTW, I singed up for monthly donations...cheers to all.

**Comment by ThyWoof** [comment]
Non stacking is by design. We still didn’t have a chance to fix the tooltip. Thanks for reporting.
