### ISSUE TITLE
Multiplayer Save Games not honoring /CE save file redirection.

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaCommunityExpansion#1518]
Was playing Solasta, "Lost Valley" with a friend.  I was hosting.  Saved a few games; called it a night.  I then tried to load my previous single player Save Games but my UI now only gives me the option to load our multiplayer saves.

Multiplayer looks to be dumping all its saves into C:\Users\[username]\AppData\LocalLow\Tactical Adventures\Solasta\Saves instead of finding and populating the correct subfolder.  I suppose I could temporarily relocate the multiplayer saves, but that's a big nuisance to do every time I want to single player vs. multiplayer.

Both the friend and I have identical configurations and versions of CE.  1.381 b Public (the XBOX update from yesterday).

PS.  If at all possible we'd love to be able to play in multiplayer with 6 characters.  4-mode sucks.  I would rather see that figured out by CE before any/all new classes, races, etc.  Thanks for all your hard work!

**Comment by ThyWoof** [comment]
Fixed
