### ISSUE TITLE
Warlock 1 / Paladin 5 Smite Bug

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaCommunityExpansion#1547]
I have a level 6 character that I just recently respec'd as a Warlock 1 / Paladin 5.  With every attack (turn and reaction), when I hit, if I choose to Smite the game hangs because it prompts me to pick the level of spell slot I want to spend (to Smite), and everything becomes unselectable.

![War1-Pal5_SmiteBugSS1](https://user-images.githubusercontent.com/101536157/178892816-92015fcb-8dc6-4a01-80a2-a6262be0f93e.jpg)
![War1-Pal5_SmiteBugSS2](https://user-images.githubusercontent.com/101536157/178892821-c43762ff-b915-4b48-b2bf-0caea68f8e37.jpg)
![War1-Pal5_SmiteBugSS3](https://user-images.githubusercontent.com/101536157/178892828-7aa618fb-2b73-4939-9db2-b670f608e8ae.jpg)

**Comment by ThyWoof** [comment]
Thanks for the report and screenshots but it would be much easier if you could share your save file with us, just before the smite attack.

**Comment by gobsmacked1** [comment]
Not sure what the problem was.  I was consistently reproducing it--now I can't.  I even went back and loaded the previous SAV from the original fight where I first noticed, and now Smite is working even there.  I guess maybe my client was bugged, and I must've since closed/reopened it.  Thanks.
