### ISSUE TITLE
Pact Magic/Spellcasting Slots issue

### ISSUE THREAD

**Issue by Rosgath** [SolastaMods/SolastaCommunityExpansion#1556]
So this is something I've noticed in my current playthrough. I'm playing a Paladin/Warlock Multiclass and it seems like it is coded to ALWAYS use Warlock spellslots first. While this is normally not a big deal, there are times where I'd rather just use a level 1 Paladin slot to smite with or to cast a spell with. The problem is, Warlock Slots are ALWAYS used first, even if I try to cast a level 1 Paladin spell (such as Divine Favor). This can be a pretty big waste since some spells don't gain any benefit from upcasting. Additionally, if you choose to smite with a 1st level slot, it will perform a first level Smite even if your Warlock slots are second level (though it will consume your second level Warlock slot).

RAW if you have both types of slots you can choose which kind you use. This feels like it will likely affect any spellcasters multiclassing with Warlock.

**Comment by ThyWoof** [comment]
You can SHIFT click to use spell slots instead of pact slots. Only on non mp game.
