### ISSUE TITLE
Level 11 Monk

### ISSUE THREAD

**Issue by Admiralbrad** [SolastaMods/SolastaCommunityExpansion#1560]
Distant Hand Ki Pop-Up broken after leveling to level 11 and the advanced version.  Stunning Arrow works, but selecting any of the distant hand options such as Knockdown or Distract causes the interface to crash preventing further actions.  Very Repeatable.

**Comment by ThyWoof** [comment]
Share a save please.

**Comment by Admiralbrad** [comment]
Sorry.  It is not doing it today.  Not sure what happened.  It started right after the level up and lasted until I stopped playing last night.  I never rebooted the game (just F9 to load latest save).  This morning I cannot repeat the issue.
