### ISSUE TITLE
Tinkerer Flame Artillery Construct won't despawn

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaCommunityExpansion#1597]
Duration says one hour.  I've long-rested at least three times and this guy won't despawn.  The other constructs so far do despawn correctly.  Not sure if my game is bugged or this spell is.  Thanks.

[LongRest.zip](https://github.com/SolastaMods/SolastaCommunityExpansion/files/9332534/LongRest.zip)
.

**Comment by ThyWoof** [comment]
I haven't wrote Tinkerer. It certainly needs a deep review but nothing will happen until TA releases the 3 remaining SRD classes.
