### ISSUE TITLE
Option for Paladin to only smite on crits

### ISSUE THREAD

**Issue by ChrisPJohn** [SolastaMods/SolastaCommunityExpansion#161]
Sporeking97
...
And on that topic, I'd love for an option to force divine smite to only prompt you on crits, rather than EVERY hit.

**Comment by RedOrcaCode** [comment]
GameLocationBattleManager.HandleCharacterAttackDamage is where smites are handled. Divine Smite has SpendSpellSlot as its TriggerCondition. Unfortunately, the behavior is mostly hard-coded in HandleCharacterAttackDamage, so you'd probably need multiple patches (or Transpiler) to get this working. This feature feels too niche to justify that much hackery.

**Comment by ThyWoof** [comment]
Transpiler isn’t working on this particular method FYI. There are some limitations on how transpiler work and here specifically instead of dumping the full method code it only does for the first 30 or so codes

**Comment by ThyWoof** [comment]
We could instead trap `CharacterReactionItem.Bind(ReactionRequest reactionRequest, GameObject observer)` or even earlier at `ReactionModal.ReactionTriggered(ReactionRequest request)`

**Comment by ThyWoof** [comment]
This would require us to fully copy HandleCharacterAttackDamage code and patch the block that tests for spell sourced damage. I would rather not touch this method at all. I even requested a couple of changes here from TA DEV team to avoid MC to patch it as well [MC does to support Wildshape scenarios but confirmed I won't need it anymore on an upcoming patch after DLC release]
