### ISSUE TITLE
Select an item screen - allow multiselect

### ISSUE THREAD

**Issue by PhilPJL** [SolastaMods/SolastaCommunityExpansion#242]
I would like to select all diamonds, for example

![image](https://user-images.githubusercontent.com/271656/146437011-a75850f3-0065-478b-b54a-3744a5295d15.png)

**Comment by ThyWoof** [comment]
I’m almost done on this one

**Comment by ThyWoof** [comment]
I parked this one as it might be wiser to wait for next DLC
