### ISSUE TITLE
Add an icon to a scroll to indicate if it's usable by that character

### ISSUE THREAD

**Issue by PhilPJL** [SolastaMods/SolastaCommunityExpansion#416]
In the inventory panel show which scroll can or cannot be used by that character.

![image](https://user-images.githubusercontent.com/271656/148661606-fc3d37db-5fd3-46e9-9660-d209ec7bc699.png)

**Comment by ThyWoof** [comment]
TA fixed a lot of bugs on how these additional icons display on 1.3.x branch. It might be a good time to revisit it.
