### ISSUE TITLE
Add CR filters to select a creature screen

### ISSUE THREAD

**Issue by PhilPJL** [SolastaMods/SolastaCommunityExpansion#502]
Could do with either filters or sorting on CR.

![image](https://user-images.githubusercontent.com/271656/149809387-f410d58c-23d7-43c0-8cdb-27e3632daf8f.png)

**Comment by ThyWoof** [comment]
I believe we touch these already on 2 toggles under Dungeon Maker. We could always sort results there if not.

**Comment by ThyWoof** [comment]
won't do.
