### ISSUE TITLE
Feature request: Haste action as seperated action.

### ISSUE THREAD

**Issue by dolenam317** [SolastaMods/SolastaCommunityExpansion#607]
Currently in game haste action is overlayed by main action i.e you cannot use the attack action granted by haste and then ready your main action.   Another thing is if you ready your action you turn is ended automatically regardless you still have haste action. IMO seperated main action and haste action bring fun and tatical choice. 

Another thing is sneak attack as a seperated action so duel wielding rogues dont have to waste their sneak attack on dying enemies. Typical scenario is my melee rouge is stand besides my tank and can reach an dying foe and a healthy one. The rogue wants to use bonus attack action to finish the dying foe without trigger sneak attack and use the main attack action to stab healthier one.

Finally as other thing in CE both of the changes are optional so it wont impact other who want vanilla things.

**Comment by DubhHerder** [comment]
Haste:
Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the **Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action**.

When the spell ends, the target can't move or take actions until after its next turn, as a wave of lethargy sweeps over it.
*****

Haste only grants restricted options for the action and a ready action isn't included. The games implementation is correct. If somebody decides to add the alteration, it should be marked as homebrew

The way sneak attack is implemented in the game it might not be simple to limit it to a particular attack button, you might end up with a pop-up for every attack like sorcerer metamagic option pop-up or paladin smite option pop-up

**Comment by ThyWoof** [comment]
@DubhHerder , I’ve been use SHIFT click on UI to change behavior of long / rest slots consumption when a MC Warlock casts a spell. I’ve been considering CTRL click for other QoL changes like stealth damage or sorcerer metamagic display. If one CTRL click on these scenarios we disable the sneak attack consideration. Same idea to avoid annoying metamagic sorcerer popup

**Comment by DubhHerder** [comment]
sorry for the confusion on ready action on main action rather than haste action.  I'm not sure how straightforward it would be to completely separate the haste action from the main action, seems like it would have significant knock on effects on the UI and action options. Best of luck to whoever takes it on. 

Would that CRTL /SHIFT click approach for all MC combinations?  A dedicated click button for each class with similar features?

**Comment by dolenam317** [comment]
@DubhHerder I dont know for sure but based on how dodge button work I think if we prevent ready on main action automatically end character turn we might achieve the same result ?

**Comment by DubhHerder** [comment]
yeah that might be much simplier than i was thinking. Based on CharacterActionDodge.cs, maybe commenting out/altering the following in CharacterActionReady.cs is enough: 
`    service.Battle.FiniteStateMachine.RequestStateChange(typeof (BattleState_TurnEnd), (object[]) Array.Empty<object>());`

**Comment by ThyWoof** [comment]
Not simple to do as this is an ienumerator method
