### ISSUE TITLE
Feature Request: Option to Nerf Blindness to Tabletop Levels

### ISSUE THREAD

**Issue by mattelkinsTC** [SolastaMods/SolastaCommunityExpansion#741]
The Blindness spell in tabletop grants a resave every round; in Solasta it does not. Removing this limitation takes it from a solid spell to a dominant strategy, since it applies a fairly debilitating condition without requiring concentration. This is more on par with (in tabletop) a 5th-level casting of Bestow Curse, but at the cost of only a 2nd-level spell slot. It would be nice if there were an option to patch it to match tabletop rules.

**Comment by Redst0neFlux** [comment]
This is still an issue.
[The blindness definition](https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/Diagnostics/OfficialBlueprints/SpellDefinition/Blindness.json) has "canSaveToCancel": false, (line 87)
when it should be true
