### ISSUE TITLE
Feature Request: Make 5th+ Level Bestow Curse Not Require Concentration (Per Tabletop Rules)

### ISSUE THREAD

**Issue by mattelkinsTC** [SolastaMods/SolastaCommunityExpansion#742]
In tabletop, Bestow Curse does not require concentration if cast with a 5th-level spell slot or higher. In Solasta this does not seem to be the case. It would be nice if it matched tabletop (or if there an option to make it match by preference), as this is one of the primary selling points of the spell.

**Comment by PhilPJL** [comment]
@mattelkinsTC If you have the DLC can you test our fix #921 when merged?

**Comment by mattelkinsTC** [comment]
I would, but when I switched from Dev branch to Beta, I can no longer compile. There are 5 missing assemblies all starting with Ak.Wwise (e.g. Ak.Wwise.Api.WAAPI.dll). Googling shows those to be part of Unity; I don't actually have Unity installed (it wasn't necessary on Dev branch). I also have essentially no experience with Unity, so I might be misdiagnosing the issue.

**Comment by ChrisPJohn** [comment]
I believe the Ak dlls are included in the 1.3.X game builds. What version of the game are you running?

**Comment by PhilPJL** [comment]
@mattelkinsTC Yes sorry, you need latest unreleased version to build the beta branch.  I'll see if we can add this change to dev.

**Comment by mattelkinsTC** [comment]
Looks like I'm running 1.2.15, with the sorcerer and primal calling DLCs. I didn't even know one could get access to the unreleased versions! Anyway, I'm happy to test if it easy enough to set it up on dev or otherwise, but I don't want to be a drag if it is difficult to do.
