### ISSUE TITLE
Feature Request: Option to Nerf Heighten Spell to Tabletop Levels

### ISSUE THREAD

**Issue by mattelkinsTC** [SolastaMods/SolastaCommunityExpansion#743]
In tabletop rules, heighten spell applies to a single save at the time of casting. Even with this limitation it is one of the top-tier metamagics. In Solasta, it applies to all saves for the spell, both at the time of casting and on subsequent resaves, if applicable. This makes it extremely powerful. It would be nice if there was an option to reduce it to tabletop levels.

**Comment by ThyWoof** [comment]
This is too hard to do with the current engine.
