### ISSUE TITLE
Level 20 features: Barbarian: Persistent Rage

### ISSUE THREAD

**Issue by ChrisPJohn** [SolastaMods/SolastaCommunityExpansion#77]

**Comment by DubhHerder** [comment]
**Feature :**
Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.
**Suggested Implementation :**
create a new presistent rage power that replaces rage power via overriddenPower that directs to a new condition with a duration of  Permanent, Day or UntilLongRest etc.

**Comment by ThyWoof** [comment]
working on it...

**Comment by ThyWoof** [comment]
Request sent for review

**Comment by RedOrcaCode** [comment]
Note that rage is still capped at 1 minute, even with Persistent Rage.

> Beginning at 15th level, your rage is so fierce that it ends **early** only if you fall unconscious or if you choose to end it.

It still ends after 1 minute, it just now ignores the following part of the Rage feature:

> It ends early [...] if your turn ends and you haven’t attacked a hostile creature since your last turn or taken damage since then.

**Comment by DubhHerder** [comment]
That's probably my fault for pointing zappa in the wrong direction with a bad suggestion after I misread the feature. 

For the actual feature, I would have assumed that the ConditionRaging would have an attribute like the following
` "specialInterruptions": [RuleDefinitions.ConditionInteruption.NoAttackOrDamagedInTurn]`
but it looks like RuleDefinitions.ConditionInteruption.NoAttackOrDamagedInTurn is not used at all, just an enum at the moment. 

Instead it looks like the code in `GameLocationCharacter.StartBattleTurn` just removes the "ConditionRaging" if no damage or attack happened in the last round so maybe just having an overridden power with a slightly different name is enough to maintain rage for the full minute. i guess new versions of PowerBarbarianRageStop and PowerBarbarianRageStart pointing to the slightly different named condition might be enough. I'll have a go at this
