### ISSUE TITLE
Level 20 features: Wizard: Overchannel

### ISSUE THREAD

**Issue by ChrisPJohn** [SolastaMods/SolastaCommunityExpansion#86]

**Comment by DubhHerder** [comment]
title should be "level 14 feature: Evocation subclass: Overchannel"

**feature :**
At 14th level, you gain a feature granted by your Arcane Tradition.

OverchannelPHB p117Starting at 14th level, you can increase the power of your simpler spells. When you cast a wizard spell of 1st through 5th-level that deals damage, you can deal maximum damage with that spell.The first time you do so, you suffer no adverse effect. If you use this feature again before you finish a long rest, you take 2d12 necrotic damage for each level of the spell, immediately after you cast it. Each time you use this feature again before finishing a long rest, the necrotic damage per spell level increases by 1d12. This damage ignores resistance and immunity.

** suggested implementation **
adapt `PowerTraditionShockArcanistArcaneShock` which offers a similar damage maximization at cost feature. A condition could be added after first use that lasts until a long rest and a new `FeatureDefinitionAdditionalDamage` trigged by `requiredTargetCondition` could inflict the damage when the condition is detected. 

It's possible that the multiple `ConditionBackFromTheDead` approach from the devs shows how to best implement scaling condition effects if another simplier method via additionalDamageType or effectform etc within a ConditionDefinition is not possible

**Comment by ThyWoof** [comment]
TA will increase cap level on an upcoming DLC. No need to waste time on 14 anymore.
